[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"

[".config/alacritty/themes"]
type = "git-repo"
refreshPeriod = "168h"
url = "https://github.com/alacritty/alacritty-theme"

[".emacs.d"]
type = "git-repo"
url = "https://github.com/doomemacs/doomemacs"
refreshPeriod = "10000h"

# [".config/memo/_posts"]
# type = "git-repo"
# refreshPeriod = "1h"
# url = "https://github.com/runoshun/my-memos"
