[colors]
background = '#1d1f21'
foreground = '#c5c8c6'
selection-background = '#1e1f22'
selection-foreground = '#b7bcba'
cursor = '#b7bcba'
black = '#1d1f21'
red = '#cc6666'
green = '#b5bd68'
yellow = '#f0c674'
blue = '#81a2be'
magenta = '#b294bb'
cyan = '#8abeb7'
white = '#c5c8c6'
light_black = '#373b41'
light_red = '#d54e53'
light_green = '#b9ca4a'
light_yellow = '#e7c547'
light_blue = '#7aa6da'
light_magenta = '#c397d8'
light_cyan = '#70c0b1'
light_white = '#eaeaea'
