[tools]
usage = "latest"
deno = "1.46.3"
python = "3.11"
node = "22"
github-cli = "latest"
jq = "latest"
yq = "latest"
awscli = "2"
ruff = "latest"
"npm:@biomejs/biome" = "latest"
"npm:zx" = "latest"
lazygit = "latest"
neovim = "0.10"
ripgrep = "latest"
starship = "latest"

[tasks.cleancache]
run = "echo hello"

[settings]
experimental = true
