[tools]
deno = "2.2"
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"

[tasks.start]
run = """
deno run --allow-net --allow-read --allow-env --allow-write proxy.ts
"""

[tasks.claude]
run = """
deno --allow-run --allow-env --allow-write --allow-read main.ts
"""

[tasks.check]
run = """
#!/bin/bash
deno lint && deno fmt --check && deno check ./src
"""

[tasks.test]
depends = ["check"]
run = """
#!/usr/bin/env bash
set -euo pipefail

# Load environment variables from .env, if present
if [ -f .env ]; then
  source .env
fi

: "${OPENAI_API_KEY:?Need to set OPENAI_API_KEY}"
: "${ANTHROPIC_API_KEY:?Need to set ANTHROPIC_API_KEY}"

# Start the proxy server in the background, logging to proxy.log
deno run --allow-net --allow-env --allow-read src/proxy.ts --debug &> proxy.log &
proxy_pid=$!
trap 'kill "${proxy_pid}"' EXIT

echo "Waiting for proxy to start on http://localhost:8000..."
sleep 2

echo "Running test_anthropic_sdk.ts against proxy..."
export ANTHROPIC_BASE_URL="http://localhost:8000"
deno run --allow-net --allow-env --allow-read src/e2e_test.ts 2>&1

echo "Tests finished."
"""
