[colors.primary]
background = '#1d1f21'
foreground = '#c5c8c6'
dim_foreground = '#707880'
bright_foreground = '#eaeaea'

[colors.normal]
black = '#1d1f21'
red = '#cc6666'
green = '#b5bd68'
yellow = '#f0c674'
blue = '#81a2be'
magenta = '#b294bb'
cyan = '#8abeb7'
white = '#c5c8c6'

[colors.bright]
black = '#373b41'
red = '#d54e53'
green = '#b9ca4a'
yellow = '#e7c547'
blue = '#7aa6da'
magenta = '#c397d8'
cyan = '#70c0b1'
white = '#eaeaea'

[colors.dim]
black = "#151718"
white = "#707880"
red = "#a54242"
green = "#8c9440"
yellow = "#de935f"
blue = "#5f819d"
magenta = "#85678f"
cyan = "#5e8d87"
